# A minimal left prompt
format = """$directory\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$character"""

add_newline = false
[line_break]
disabled = true

[character]
vimcmd_symbol = '[󰕷](bold green)'

[directory]
truncation_length = 3
truncate_to_repo = true
style = 'cyan'
before_repo_root_style = 'dimmed cyan'
repo_root_style = 'cyan'
read_only = " 󰌾"


[git_status]
ahead = '[${count}⇡](bold green) '
diverged = '[⇕](bold 208)[${ahead_count}⇡](bold green)[${behind_count}⇣](bold bright-red) '
behind = '[${count}⇣](bold bright-red) '
untracked = '[${count}? ](bold 208)'
modified = '[${count}~ ](bold 208)'
renamed = '[${count}» ](bold 208)'
staged = '[${count}+ ](bold green)'
deleted = '[${count}✘ ](bold bright-red)'
stashed = ''
format = "$all_status$ahead_behind"

[cmd_duration]
disabled = true

[time]
disabled = true
